Use `assertEqual` instead of `assertEquals` (#2493)
Fixes the following failure:

```
fastbuild/bin/tools/bundletool/bundletool_test.runfiles/_main/tools/bundletool/bundletool_test.py", line 146, in _assert_zip_contains
    self.assertEquals(
    ^^^^^^^^^^^^^^^^^
AttributeError: 'BundlerTest' object has no attribute 'assertEquals'. Did you mean: 'assertEqual'?
```