Fix permissions with test host and tree artifacts
Previously because the `cp` was acting on a symlink, the TMP_DIR would
only contain copies of the symlinks. Then when we ran `chmod` on them,
they wouldn't change the permissions at all. Using `-L` forces them to
copy the directories, instead of the symlinks.

This problem caused xctestrunner to not be able to write directories
inside the test host:

```
OSError: [Errno 13] Permission denied: '/tmp/test_runner_work_dir.0XWONr/TEST_ROOT/TestHost.app/Frameworks/XCTest.framework'
```