Fix `watchos_unit_test` incorrect handling of `test_host` (#1645)
Before this change:
```
ERROR: /Users/brentley/Developer/rules_xcodeproj/examples/integration/watchOSAppExtension/Test/UnitTests/BUILD:4:18: //watchOSAppExtension/Test/UnitTests:watchOSAppExtensionUnitTests: no such attribute 'bundle_loader' in 'watchos_unit_test' rule
```

(cherry picked from commit 40a8e05c3a1f83f2d1d8b6c128fc498528b831bd)