Fix module name in example/multi_platform/Buttons
I found this target got error because its `module_name` was wrong.

```sh
bazel build //examples/multi_platform/Buttons:ButtonsStaticFramework
```

```
Error in fail:
error: Found swift_library with module name 'Buttons' but expected 'ButtonsStaticFramework'. Swift static frameworks expect a single swift_library dependency with `module_name` set to the same `bundle_name` as the static framework target.
```

This PR will

- Fix `bundle_name` attribute (Use the same name as `ButtonsLib`)
- Add test case to `ExamplesBuildTest`